spring:
  application:
    name: snowflakeStudy

  messages:
    encoding: UTF-8

  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/snowflake


  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
